# Generated by Django 5.0.4 on 2024-04-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_brand_alter_carromodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='carromodel',
            name='photo',
            field=models.ImageField(null=True, upload_to='app/'),
        ),
        migrations.AddField(
            model_name='carromodel',
            name='plate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
