# Generated by Django 5.0.4 on 2024-04-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_carromodel_photo_carromodel_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carromodel',
            name='photo',
            field=models.ImageField(default=1, upload_to='app/'),
            preserve_default=False,
        ),
    ]
