# Generated by Django 5.0.4 on 2024-04-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_carinvetory'),
    ]

    operations = [
        migrations.AddField(
            model_name='carromodel',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
